language: node_js
node_js:
- stable
env:
  global:
    secure: wNoCkQJDKUe+8iU5qw6qi1C1CxP9dBFlqWpgpinEbi+qkeI009O7DUY2f9ZMKJCFwqXKMm+oMDcJQo/oe70TOvn/kBQw3cLchfG9cLtfYMUF/wvwKQGu0LkVUdvCm3fwEbyJ0AkYkd4yGKAQDsZUC77QYktEdlLrovyCgJQbtxXsToOMxKHG1h1xsWZ16LIu53hecoEL80lUhoMjzI5Y9PUgFf/4jjcXz/IuwFznrfTa6/DsSn72gHjtTwa7uJr6qvtGakQB5EapGMVJe8nHgc5J7zYrH2bj3LxHDktLYmcd3s2D/efyPiFgKxLBAcRaLJnbKAKM5Csv+wsmAnXty8yEW3Z6EeEEkU08ECnlBkKQl2HPyRASP1I69AaSaYpj+DF+rz18SUdp0cs8yJH47LzXOL81Oy4rpZXJODCkmPUMFTN66l3wjaRnEDGvVMpccpxgl7uxi7mXxkQcjND+54Z61VVuj4ye7KP3KPFkslO3XZwGxlfOl9xXwtaGe/d1c4gG8OPIuVHUCsPim0UKPgDNDqfe90vvrQv5LP9vHEKsOnn3DK7DH9vMLgrznaJIPpU6IjItsLQVuOPlTke/BpY9oxjerSnShKnuO+ox7jLJBiJboDL8LBhw/hLkfCOSbRdPm3nLi/oBM4cmA8SdRExq0sqYPB8qIWrheQ3l/qU=
